services:
  xtoken:
    image: cracktc/xtoken
    container_name: xtoken
    restart: always
    ports:
      - 8080:80
    environment:
      - TOKEN=<token>
      - PROXY_LIST_URL=<url to socks5 proxy list>
      - AUTHORIZATION=<authorization header>
